name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 21.1.1
          branches: |
            [
              "+([0-9])?(.{+([0-9]),x}).x",
              "main",
              "next",
              "next-major",
              { "name": "beta", "prerelease": true },
              { "name": "alpha", "prerelease": true }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}